version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    image: brainchain-backend:latest
    container_name: brainchain-backend
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - RIZA_API_KEY=${RIZA_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - brainchain-network

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    image: brainchain-frontend:latest
    container_name: brainchain-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - brainchain-network

networks:
  brainchain-network:
    driver: bridge