version: '3.8'

services:
  backend:
    image: srijan271/brainchain-backend:latest
    container_name: brainchain-backend
    ports:
      - "80:8000"  # Your backend is mapped 80 -> 8000
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - RIZA_API_KEY=${RIZA_API_KEY}
      - TAVILY_API_KEY=${TAVILY_API_KEY}
    networks:
      - brainchain-network

  frontend:
    image: srijan271/brainchain-frontend:latest
    container_name: brainchain-frontend
    ports:
      - "3000:8501"  # Your frontend is mapped 3000 -> 8501
    depends_on:
      - backend
    networks:
      - brainchain-network

networks:
  brainchain-network:
    driver: bridge
